name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manually running via Actions tab.
  workflow_dispatch:
  
jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //...

